# Data Management

**Summary**: The organization, preservation, and sharing of data are very important aspects of analysis and research although the current methods for doing this are not satisfactory. Intermediate results and data transformations are not maintained alongside original data which impairs reproducibility. A framework(s) is needed to maintain experimental data, code, and notebooks. 


## Data Hosting

The primary method of managing data involves the use of [Emory Box](https://emory.account.box.com/login) in conjunction with [RedCap](https://www.project-redcap.org/) although no one interviewed believes Box to be ideal or particularly desirable outside of its approved use for hosting health data. The data being hosted on Box is typically distributed to collaborators and analysts who in turn maintain personally transformed versions of the data and associated intermediate results. It is rare that those results and transformed datasets are re-integrated back alongside the original data in a manner that facilitates reproducibility. While study data is being maintained in RedCap there are an increasing number of associated experimental data types that aren't appropriate for tracking in RedCap thus they need to be maintained separately on Box. However, the Box resource cannot be computed against. Some faculty do use R Notebooks for reproducibility but point to the problem of keeping track of results generated by others who might "touch"" the project and preserve their own scripts and transformed data on their laptop. Given that shuffling data around is largely a manual process, trying to “work back” from results to the original data is challenging.

## Source Code Maintenance

Many of the reference software pipelines for Microbiome analysis (as well as other data types) are obtained from literature references, training, and/or vignettes that might be supplied with a given software package. It is expected that changes will be made to scripts simply to accommodate local data sources which might very well lead to questions and interactions with package authors, statisticians, and more generally anyone who might be able to help the research bypass roadblocks. Thus, the state of a script or code can vary greatly at any time depending on where in the process things are. These scripts are almost always maintained on personal laptops or desktop computers although at least one person uses Git and GitHub to archive scripts. Even so, the scripts are typically highly customized for a specific project. Also, GitHub is for maintaining code changes and *not* data thus it is inappropriate to host data and results (intermediate or final) along with the code. It's also true that GitHub exists to encourage collaboration and co-development though not everyone who would use Git or GitHub feels that the code is in a "good enough" state to push to a repository for general use and inspection. 

## Notebooks and Reproducible Research 

Some faculty are using R Notebooks to capture a narrative alongside the code used to generate results. These notebooks are prime candidates for registration on GitHub as it allows others to benefit from the work and permits easy retrieval of previous versions. Of course, some do not wish to share their code for various reasons such as that is in development. Another reason is that the end result is simply a minor variation of a published pipeline (e.g. Qiime2 or dada2) in response to specific sequencing problems or situations that might not relate to another PIs project. Some labs have in fact maintained scripts in GitHub or on the Costas website at http://enve-omics.ce.gatech.edu/ although the practice is not prevalent. 

## Reproducible Research

Reproducing research is major concern that has been placed aside in favor of simply being able to get analysis accomplished (which itself has been a challenge). In short “the data can’t grow roots anywhere” so being able to integrate all intermediate results, let alone track the provenance and chain of custody thereof, has been very challenging outside of the simplest of projects. A larger issue exists in knowing the "best practices" associated with creating reproducible resources. Some faculty do know about "notebooks" in R and Python and see the value in using them although integrating a personal notebook with that of an analyst or collaborator remains a challenge. Keeping copies of "cleaning" scripts in addition to analysis pipelines is a priority though concern remains at being able to reproduce results if and when key personnel leave the department. 




