# Computation

**Summary:** Computation underlies research analytics though no official resource exists within the school, which can be challenging. Faculty use whatever resources they can find and will leverage relationships (personal and professional) to work around the issue. Lots of code and data winds up on laptops which works against reproducibility, security, and project continuity. 

Computation is not something that was directly mentioned by most faculty simply because it is generally considered to be an underlying component to data management and analysis and is therefore generally *not* the first topic referenced when discussing challenges. However, everyone understands that analysis and data manipulation must occur "somewhere" which is why some faculty leverage personal and professional relationships (Math/CS, Georgia Tech, Winship Cancer Institute) to accomplish the computation. Unfortunately, these resources aren't necessarily available to other School of Nursing Faculty or if they are now, might not be if the SON person were to leave. 

## Data Management and Computation

Smaller projects can in fact be accomplished using laptops and desktops though the trend has rapidly moved towards more samples per project thus being able to easily and conveniently compute against data sources is very important. This is a major limitation of Emory Box in that the data cannot be directly accessed via software. It might be more convenient for it to be in Amazon S3 bucket or a folder attached to a compute node, or in a system such as [DNANexus](https://www.dnanexus.com/) or [Seven Bridges](https://www.sevenbridges.com/) both of which are enterprise frameworks for data management, analysis, and computation. These are currently being considered by WCI in support of their ORIEN http://oriencancer.org/#about  project though it is quite possible that the School of Nursing could benefit from using the license also since it would provide a standard tool for management, analysis, and compute. However, embracing these tools would still involve formal training and orientation to ensure productivity. 

## Cloud vs Local Resources

All of those interviewed are aware of the importance of resources such as Amazon or Google but lack the training to reasonably approach these resources directly unless “chaperoned” by someone more knowledgeable or by involving a funded collaborator. A minority of those interviewed express an interest in knowing how to configure cloud resources at a "nuts and bolts" level though most do not see immediate value in that. Although they do understand that being more facile at the UNIX command line and with R and Python can only help them. In the end, faculty are not fixated on a specific architecture or method of computation as long as it is readily available and accessible using standard, documented methods. Many faculty are getting their computational work done "by hook or by crook" so they are open to something more generally accessible that is setup according to a standard and doesn't require them to "jump around" to different resources throughout the course of the project.  

### Onboarding Cloud Support

On boarding To the Cloud is a problem. The cloud's ability to match the scope of most any research project is indeed a true convenience which, however, requires significant knowledge to fully exploit. Knowing how to responsibly provision storage, "spin up" instances, create databases, and effectively close out projects are important skills. It has been difficult getting a clear message from the institution as to when a service offering would be official and what precisely the support mechanism would provide particularly as it relates to hands on support and assistance with managing cloud-based instances. A soft opening was announced for Fall of 2018 though the service arrival date is now "early 2019". Investigators will need assistance and/or proxies to handle the foundational work which would typically involve students although a more official, permanent, and reliable form of support is essential since students and postdocs eventually move on. In absence of enthusiastic end-user support it will likely not be heavily used except by those already knowledgeable and/or funded specifically to the do the work. Some reference the TARDIS cluster as being representative of a computational resource that was poorly supported from the user point of view. Questions went unanswered nor was there lcoal Emory support except in the form of project or product managers who did not offer actual support of assistance. Investigators were expected to "self-educate". The hope is that this approach does not persist relative to the Amazon offering. 

### Post Project Data Archival 

Research evolves over time and involves input from collaborators (statisticians, analysts, bioinformatics etc.) which means that the data must remain resident on the cloud as the project evolves. This ongoing occupancy involves costs and while someone could move the data off to cheaper storage and then move it back to EBS, this is inconvenient and also interrupts the continuity. Local resources are catch as catch can (frequently by personal arrangements) but charges don't accrue although if the person leaves then access to the data and resource, along with a description thereof go missing. Being able to maintain data on the Amazon cloud is an interest especially with the attractive life cycle management tools that can push out data to Glacier for long term, inexpensive archical. Addiitonally, Amazon provides versioning, flexible permission schemes, and tiers for infrequently accessed data though intelligent use of these features will require support from the institution. It is not apparent that LITS is willing to offer this especially given that the perferred storage platform is the Isilon storage system which has no Glacier-like capability. Putting data in Box is "okay" but 1) it cannot be computed against and 2) if the institution is truly moving towards a cloud-first solution then investigators should be allocated Amazon S3 storage equivalent in size to the free Emory Box offering. 


## Desktop Support for Open Source Analysis Tools

Faculty have expressed concern at the level of IT desktop support they receive which is limited when considering that they need to conduct analyses on their desktops using open source tools. Put simply, Nursing School IT does not appear to be incentivized to help researchers. Being able to install and update opensource tools (e.g. R, Python, add-on packages) AND receive troubleshooting assistance is a common need although it has been quite difficult to obtain such help. While faculty would gladly use a more fully configured computational resource specifically customized for analysis and data manipulation there will always be a need for desktop computation simply to try things out and/or do trial runs of pipelines found in literature. To this end having someone in IT who is motivated to do this would be helpful. Note that faculty are NOT expecting the IT group to provide research advice or debug programming issues. However, they should be able to troubleshoot basic installation problems and be able to assist in the updating of packages and generally be aware of desktop issues as it relates to research.

## General IT Support

The focus of the interview process was primarily to collect impressions about the research process with a general focus on data management, analytics, and related issues. However, it wasn't surprising that "side" discussions about IT emerged as many of the faculty weren't/aren't entirely clear on the role that group plays in research matters if any. Generally, expectations have been, and continue to be, low about what IT can do to facilitate research though it was also agreed that this should not necessarily be acceptable - especially if Nursing IT receives budget to assist faculty beyond merely reproducing LITS type services locally. Simply because the group has not been motivated in the past to help researchers should not then mean that the group should not be reconfigured around priorities of benefit to investigators. This could be useful in the sense that a reconfigured group could maintain local servers and databases but, again, this assumes a commitment to a new direction that would most likely require new (or retrained) personnel. Training on Amazon in particular should be a priority for IT.

## Databases and Applications

Some faculty would want to do this in support of a research project though by far the more pressing need relates to analytics, statistics, and omics. Deploying web-enabled apps and database is actually a very common interest in research departments across the institution. Unfortunately, there is no common Emory service for this which then means that apps must be locally developed and maintained on local servers. Obviously, Amazon could be used as a foundation for apps, but ongoing cost is a concern. Still, investigators would pay if the resource were well supported, backed up, and maintained. In absence of this, the School would have to provide server space (backups, patches, upgrades, security auditing) as well as DBA (Database Administration) support for app hosting which in turn would require administrators. These administrators would NOT necessarily have to have research or analytics skills so if the IT group were reconfigured to provide more services then this might be one of them. 
